### ISSUE TITLE
貌似现在不行你这方法 要用Scrapy-Splash

### ISSUE THREAD

**Issue by HTMLtargetblank** [nickcxm/huilv#1]
我用Scrapy-Splash 第一次请求可以正常解析,第二次请求的结果貌似是空的 无法正常的解析!

**Comment by HTMLtargetblank** [comment]
今天尝试了一下 成功了 但是必须要用Scrapy-Splash

**Comment by nickcxm** [comment]
不好意思很久没用这个号了，在用bitbucket，最近github私有仓库免费了才来看一下
